**26/11/2020**

Now, let's start my code guide for data analysis. First things first, Numpy arrays

**27/11/2020**

Finished my indexation and selection part. Next, I will work on the arithmetic operators we can do with arrays

# Numpy

In [2]:
import warnings
import math
import numpy as np

Arrays come as one dimensional vetor or two dimensional matrices. Lets see how to transform a **List into an Array**

I'm going to cast a **matrix** by having a list of lists

In [3]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
matrix = np.array(my_mat)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now, I going to try some **Methods** and **Attributes**

**Attribute:** A variable stored in an instance or class is called an [attribute](https://docs.python.org/3/glossary.html#term-attribute)

**Methods:** A function stored in an instance or class is called a [method](https://docs.python.org/3/glossary.html#term-method) 

Some of them will be usefull to:
- Form random arrays
- Have an Identity Matrix ----> It has good mathematical proprieties
- Have my array in a different shape
- Find max and min values
- Indexation and Slicing: Similar to lists
- Arithmetic Operations

In [5]:
# arr.copy ---> in the slice part
# Some array Funtions
    # np.sqrt
    # np.exp
    # np.max
    # np.sin
    # np.log
    # np.sum
    # np.std
    # ranarr.max()
    # ranarr.min()
    # ranarr.argmax()
    # ranarr.argmin()

**I can form arrays in many different ways:**

    - With predefined values

In [6]:
np.arange(5, 17)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

    - With the same predefined values, but with a interval step

In [7]:
np.arange(start = 5, stop = 17, step = 3)

array([ 5,  8, 11, 14])

    - I can have a matrix of:
        - Zeros
        - Ones
        - Identity Matrix: defining a parameter that indicates the length of my diagonal
        
**I need to pass a tuple of (rows, columns) to have a matrix**

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

    - Now for random vectors and matrices...

In [11]:
np.random.rand(5)

array([0.79031609, 0.91705095, 0.37791414, 0.95823537, 0.0760805 ])

In [12]:
np.random.randn(5)

array([-1.94656216, -0.33067008,  0.32078113,  0.10239482,  0.28595017])

What is the difference between these last two vectors?

The first one, with the **np.random.rand()** forms an array with **random** samples that follow a **uniform distribution over 0 to 1**

The second one, with the **np.random.randn()** returns an array with numbers from a **standard normal distribution around 0 (gaussian)**

The same logic can be done to form matrices

In [13]:
np.random.rand(3,4)

array([[0.93387645, 0.55593043, 0.87523117, 0.48619927],
       [0.8167383 , 0.95178581, 0.65033657, 0.12517079],
       [0.73844275, 0.62184569, 0.37755284, 0.50312697]])

In [14]:
np.random.randn(3,4)

array([[ 0.36329136,  1.68184136, -1.33226774,  0.15463208],
       [ 0.69657668, -0.0540593 , -2.18316837, -1.332397  ],
       [ 0.67604838,  0.04453882,  0.49484488, -2.99210165]])

This last one returns random integers from an **inclusive** to an **exclusive** number. 

In my 3rd argument I can state how many numbers I want

In [15]:
np.random.randint(1, 100, 10)

array([85, 17, 23, 83, 25, 38, 47, 79, 49, 66])

Now that I create my arrays, I can use the reshape attribute to change the looks

Let's go back to the variable "matrix" that I created in the beginnig

In [16]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

This is a square matrix, with 3 rows and 3 columns. Lets rearrange it

In [17]:
matrix.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

This was not a very smooth arrangement because I need to consider the size of my matrix (= 9). Since the 9 is only divisible by 1, 3 and 9 the options were a bit limited...

So, **Rows * Columns = Total Number of Elements** 

Finally, I will look at what type of values are inside my matriz. Are they integers? Floats?

In [18]:
matrix.dtype

dtype('int32')

---

## **After I deal with creation and transformation, lets pass to a new section ==> Indexation and Selection**

This is quite similar to how to deal with lists

Lets start with a one dimensional array and work our way into a matrix

In [19]:
random_array = np.random.randint(1, 100, 10)
random_array

array([98, 81,  6, 73, 10, 25, 97, 86, 67,  8])

**Selection** is the same logic as lists

If I slice, the first number is **inclusive** the last one is **exclusive** as usual

In [20]:
print(random_array[3])
print('\n')
print(random_array[2:5])

73


[ 6 73 10]


This is where it gets interesting. Arrays have an ability called Broadcast that differs them from a normal python list.

I'm going to replace values in my array.

Then, I going to slice my array and work on that slice and you will see that the final result will also occur in my original matrix. This will by like a zoom-in on my array

In [21]:
random_array[0:3] = (0, 1, 2)

I just **replaced** the first 3 elements of my matrix (23, 27 and  39) by (0, 1 and 2)

In [22]:
random_array

array([ 0,  1,  2, 73, 10, 25, 97, 86, 67,  8])

Now, lets slice my array and assign that slice to a variable

In [23]:
slice = random_array[-3:]
slice

array([86, 67,  8])

I will change this values, just like the previous ones

In [24]:
slice[:] = (90, 60, 30)

In [25]:
slice

array([90, 60, 30])

Now, if I look to my array...

In [26]:
random_array

array([ 0,  1,  2, 73, 10, 25, 97, 90, 60, 30])

Notice that the last 3 values also changed. 

**Data is not copied, it is a view of the original array! This avoids memory problems!**

How to bypass this? Using the **copy method**

In [27]:
copy = random_array.copy()

In [28]:
copy

array([ 0,  1,  2, 73, 10, 25, 97, 90, 60, 30])

I can work in my duplicate without being concern to lose data

----

**Lets use a bigger matrix**

In [29]:
new_matrix = np.arange(1, 37).reshape(6,6)

In [30]:
new_matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

**Slice notation:** [rows,columns]

In [33]:
new_matrix[2:5, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [34]:
new_matrix[:2,:2]

array([[1, 2],
       [7, 8]])

In [35]:
new_matrix[1:,1:]

array([[ 8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24],
       [26, 27, 28, 29, 30],
       [32, 33, 34, 35, 36]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order, by pointing out the row index

In [38]:
new_matrix[[2,4,5]]

array([[13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

And we can reverse the order

In [39]:
new_matrix[[5,4,2]]

array([[31, 32, 33, 34, 35, 36],
       [25, 26, 27, 28, 29, 30],
       [13, 14, 15, 16, 17, 18]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [40]:
new_matrix > 3

array([[False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [41]:
bool_matrix = new_matrix > 13

In [42]:
bool_matrix

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [43]:
# I only get the results when the boolean that I applied to my matrix is True
new_matrix[bool_matrix]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36])

---

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.

Let's apply some basic arithmetics and some numpy functions

In [45]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
matrix + matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [50]:
matrix * matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

We can also apply a single operation to the all matrix

In [54]:
print(matrix + 5)
print('\n')
print(matrix * 10)
print('\n')
print(matrix **2)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[10 20 30]
 [40 50 60]
 [70 80 90]]


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Lets see the **functions**

In [55]:
# np.sqrt
    # np.exp
    # np.max
    # np.sin
    # np.log
    # np.sum
    # np.std

In [56]:
#Taking Square Roots
np.sqrt(matrix)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [57]:
#Calcualting exponential (e^)
np.exp(matrix)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [65]:
#The max and min value in our matrix
print(np.max(matrix))

print(np.min(matrix))

9
1


In [67]:
#Calculate the sin
np.sin(matrix)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [68]:
#Calculte logs
np.log(matrix)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [69]:
#Sum
np.sum(matrix)

45

In [70]:
#Standard deviation
np.std(matrix)

2.581988897471611

In [71]:
#Sum all columns ---> just add the axis parameter
np.sum(matrix, axis=0)

array([12, 15, 18])

In [73]:
#Sum all rows
np.sum(matrix, axis=1)

array([ 6, 15, 24])